-- begin CAKES_CAKE
alter table CAKES_CAKE add constraint FK_CAKES_CAKE_ON_PRICE_GROUP foreign key (PRICE_GROUP_ID) references CAKES_PRICE_GORUP(ID)^
create index IDX_CAKES_CAKE_ON_PRICE_GROUP on CAKES_CAKE (PRICE_GROUP_ID)^
create index IDX_CAKES_CAKE_NAME on CAKES_CAKE (NAME)^
-- end CAKES_CAKE
-- begin CAKES_CAKE_INVENTORY
alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_CAKE foreign key (CAKE_ID) references CAKES_CAKE(ID)^
alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_EXPORTED foreign key (EXPORTED_ID) references CAKES_EXPORTED(ID)^
alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_STORE foreign key (STORE_ID) references CAKES_STORE(ID)^
alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_REFRIGERATOR foreign key (REFRIGERATOR_ID) references CAKES_REFRIGERATOR(ID)^
create index IDX_CAKES_CAKE_INVENTORY_ON_CAKE on CAKES_CAKE_INVENTORY (CAKE_ID)^
create index IDX_CAKES_CAKE_INVENTORY_ON_EXPORTED on CAKES_CAKE_INVENTORY (EXPORTED_ID)^
create index IDX_CAKES_CAKE_INVENTORY_ON_STORE on CAKES_CAKE_INVENTORY (STORE_ID)^
create index IDX_CAKES_CAKE_INVENTORY_ON_REFRIGERATOR on CAKES_CAKE_INVENTORY (REFRIGERATOR_ID)^
-- end CAKES_CAKE_INVENTORY
-- begin CAKES_REFRIGERATOR
alter table CAKES_REFRIGERATOR add constraint FK_CAKES_REFRIGERATOR_ON_STORE foreign key (STORE_ID) references CAKES_STORE(ID)^
create index IDX_CAKES_REFRIGERATOR_ON_STORE on CAKES_REFRIGERATOR (STORE_ID)^
-- end CAKES_REFRIGERATOR
