alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_CAKE foreign key (CAKE_ID) references CAKES_CAKE(ID);
create index IDX_CAKES_CAKE_INVENTORY_ON_CAKE on CAKES_CAKE_INVENTORY (CAKE_ID);
