alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_EXPORTED foreign key (EXPORTED_ID) references CAKES_EXPORTED(ID);
create index IDX_CAKES_CAKE_INVENTORY_ON_EXPORTED on CAKES_CAKE_INVENTORY (EXPORTED_ID);
