alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_CAKE foreign key (CAKE_ID) references CAKES_CAKE(ID);
alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_STORE foreign key (STORE_ID) references CAKES_STORE(ID);
alter table CAKES_CAKE_INVENTORY add constraint FK_CAKES_CAKE_INVENTORY_ON_REFRIGERATOR foreign key (REFRIGERATOR_ID) references CAKES_REFRIGERATOR(ID);
create index IDX_CAKES_CAKE_INVENTORY_ON_CAKE on CAKES_CAKE_INVENTORY (CAKE_ID);
create index IDX_CAKES_CAKE_INVENTORY_ON_STORE on CAKES_CAKE_INVENTORY (STORE_ID);
create index IDX_CAKES_CAKE_INVENTORY_ON_REFRIGERATOR on CAKES_CAKE_INVENTORY (REFRIGERATOR_ID);
