alter table CAKES_REFRIGERATOR add constraint FK_CAKES_REFRIGERATOR_ON_STORE foreign key (STORE_ID) references CAKES_STORE(ID);
create index IDX_CAKES_REFRIGERATOR_ON_STORE on CAKES_REFRIGERATOR (STORE_ID);
